version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - echo "Installing dependencies..."
      - npm cache clean --force
      - npm install --legacy-peer-deps
  build:
    commands:
      - echo "Building the React app..."
      - npm run build

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/'
