// creditPointConstants.js

export const CREDIT_POINT_REQUEST_CREATE_REQUEST = 'CREDIT_POINT_REQUEST_CREATE_REQUEST';
export const CREDIT_POINT_REQUEST_CREATE_SUCCESS = 'CREDIT_POINT_REQUEST_CREATE_SUCCESS';
export const CREDIT_POINT_REQUEST_CREATE_FAIL = 'CREDIT_POINT_REQUEST_CREATE_FAIL';

export const CREDIT_POINT_LIST_REQUEST = 'CREDIT_POINT_LIST_REQUEST';
export const CREDIT_POINT_LIST_SUCCESS = 'CREDIT_POINT_LIST_SUCCESS';
export const CREDIT_POINT_LIST_FAIL = 'CREDIT_POINT_LIST_FAIL';

export const CREDIT_POINT_ALL_LIST_REQUEST = 'CREDIT_POINT_ALL_LIST_REQUEST';
export const CREDIT_POINT_ALL_LIST_SUCCESS = 'CREDIT_POINT_ALL_LIST_SUCCESS';
export const CREDIT_POINT_ALL_LIST_FAIL = 'CREDIT_POINT_ALL_LIST_FAIL'; 

export const CREDIT_POINT_BALANCE_REQUEST = 'CREDIT_POINT_BALANCE_REQUEST';
export const CREDIT_POINT_BALANCE_SUCCESS = 'CREDIT_POINT_BALANCE_SUCCESS';
export const CREDIT_POINT_BALANCE_FAIL = 'CREDIT_POINT_BALANCE_FAIL'; 
