// marketplaceSellerConstants.js
export const CREATE_MARKETPLACE_SELLER_REQUEST = 'CREATE_MARKETPLACE_SELLER_REQUEST';
export const CREATE_MARKETPLACE_SELLER_SUCCESS = 'CREATE_MARKETPLACE_SELLER_SUCCESS';
export const CREATE_MARKETPLACE_SELLER_FAIL = 'CREATE_MARKETPLACE_SELLER_FAIL';

export const MARKETPLACE_SELLER_PHOTO_REQUEST = 'MARKETPLACE_SELLER_PHOTO_REQUEST';
export const MARKETPLACE_SELLER_PHOTO_SUCCESS = 'MARKETPLACE_SELLER_PHOTO_SUCCESS';
export const MARKETPLACE_SELLER_PHOTO_FAIL = 'MARKETPLACE_SELLER_PHOTO_FAIL';

export const POST_FREE_AD_REQUEST = 'POST_FREE_AD_REQUEST';
export const POST_FREE_AD_SUCCESS = 'POST_FREE_AD_SUCCESS';
export const POST_FREE_AD_FAIL = 'POST_FREE_AD_FAIL';

export const POST_PAID_AD_REQUEST = 'POST_PAID_AD_REQUEST';
export const POST_PAID_AD_SUCCESS = 'POST_PAID_AD_SUCCESS';
export const POST_PAID_AD_FAIL = 'POST_PAID_AD_FAIL';
