// marketplaceSellerConstants.js
export const CREATE_MARKETPLACE_SELLER_REQUEST = 'CREATE_MARKETPLACE_SELLER_REQUEST';
export const CREATE_MARKETPLACE_SELLER_SUCCESS = 'CREATE_MARKETPLACE_SELLER_SUCCESS';
export const CREATE_MARKETPLACE_SELLER_FAIL = 'CREATE_MARKETPLACE_SELLER_FAIL';

export const GET_SELLER_ACCOUNT_REQUEST = 'GET_SELLER_ACCOUNT_REQUEST';
export const GET_SELLER_ACCOUNT_SUCCESS = 'GET_SELLER_ACCOUNT_SUCCESS';
export const GET_SELLER_ACCOUNT_FAIL = 'GET_SELLER_ACCOUNT_FAIL';

export const UPDATE_SELLER_ACCOUNT_REQUEST = 'UPDATE_SELLER_ACCOUNT_REQUEST';
export const UPDATE_SELLER_ACCOUNT_SUCCESS = 'UPDATE_SELLER_ACCOUNT_SUCCESS';
export const UPDATE_SELLER_ACCOUNT_FAIL = 'UPDATE_SELLER_ACCOUNT_FAIL';

export const MARKETPLACE_SELLER_PHOTO_REQUEST = 'MARKETPLACE_SELLER_PHOTO_REQUEST';
export const MARKETPLACE_SELLER_PHOTO_SUCCESS = 'MARKETPLACE_SELLER_PHOTO_SUCCESS';
export const MARKETPLACE_SELLER_PHOTO_FAIL = 'MARKETPLACE_SELLER_PHOTO_FAIL';

export const GET_SELLER_PHOTO_REQUEST = 'GET_SELLER_PHOTO_REQUEST';
export const GET_SELLER_PHOTO_SUCCESS = 'GET_SELLER_PHOTO_SUCCESS';
export const GET_SELLER_PHOTO_FAIL = 'GET_SELLER_PHOTO_FAIL';
export const UPDATE_SELLER_PHOTO_REQUEST = 'UPDATE_SELLER_PHOTO_REQUEST';
export const UPDATE_SELLER_PHOTO_SUCCESS = 'UPDATE_SELLER_PHOTO_SUCCESS';
export const UPDATE_SELLER_PHOTO_FAIL = 'UPDATE_SELLER_PHOTO_FAIL';

export const POST_FREE_AD_REQUEST = 'POST_FREE_AD_REQUEST';
export const POST_FREE_AD_SUCCESS = 'POST_FREE_AD_SUCCESS';
export const POST_FREE_AD_FAIL = 'POST_FREE_AD_FAIL';

export const POST_PAID_AD_REQUEST = 'POST_PAID_AD_REQUEST';
export const POST_PAID_AD_SUCCESS = 'POST_PAID_AD_SUCCESS';
export const POST_PAID_AD_FAIL = 'POST_PAID_AD_FAIL';
