export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST';
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL';

export const ORDER_DELETE_RESET = 'ORDER_DELETE_RESET';

export const ORDER_ITEMS_LIST_REQUEST = 'ORDER_ITEMS_LIST_REQUEST';
export const ORDER_ITEMS_LIST_SUCCESS = 'ORDER_ITEMS_LIST_SUCCESS';
export const ORDER_ITEMS_LIST_FAIL = 'ORDER_ITEMS_LIST_FAIL';

export const REVIEW_ADD_REQUEST = 'REVIEW_ADD_REQUEST';
export const REVIEW_ADD_SUCCESS = 'REVIEW_ADD_SUCCESS';
export const REVIEW_ADD_FAIL = 'REVIEW_ADD_FAIL';

export const REVIEW_EDIT_REQUEST = 'REVIEW_EDIT_REQUEST';
export const REVIEW_EDIT_SUCCESS = 'REVIEW_EDIT_SUCCESS';
export const REVIEW_EDIT_FAIL = 'REVIEW_EDIT_FAIL';

export const SHIPPING_ADDRESS_FETCH_REQUEST = 'SHIPPING_ADDRESS_FETCH_REQUEST';
export const SHIPPING_ADDRESS_FETCH_SUCCESS = 'SHIPPING_ADDRESS_FETCH_SUCCESS';
export const SHIPPING_ADDRESS_FETCH_FAIL = 'SHIPPING_ADDRESS_FETCH_FAIL';

export const CONFIRM_DELIVERY_REQUEST = 'CONFIRM_DELIVERY_REQUEST';
export const CONFIRM_DELIVERY_SUCCESS = 'CONFIRM_DELIVERY_SUCCESS';
export const CONFIRM_DELIVERY_FAIL = 'CONFIRM_DELIVERY_FAIL';
