export const APPLY_PROMO_SUCCESS = 'APPLY_PROMO_SUCCESS';
export const APPLY_PROMO_ERROR = 'APPLY_PROMO_ERROR';
export const SET_TIMER = 'SET_TIMER'; 

export const REFERRAL_SUCCESS = 'REFERRAL_SUCCESS'; 
export const REFERRAL_ERROR = 'REFERRAL_ERROR'; 
